# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-10-24 14:05:41 -0400 by graham.troyer-joy:
gem "rspec", "~> 3.8"

# Added at 2018-10-24 14:11:08 -0400 by graham.troyer-joy:
gem "require_all", "~> 2.0"
